#!/bin/bash
#
# Install UDFs into Trino.
#
# Usage: install-udfs [trino_url]

set -euo pipefail

# URL of our Trino server.
trino_url="${1:-"http://localhost:8080"}"
#echo trino_url: "$trino_url"

until curl -s "$trino_url/v1/info" | grep -q '"starting":false'; do sleep 1; done
trino --file "/etc/trino/trino_compat.sql" "$trino_url"
