-- Quoted identifiers.

CREATE OR REPLACE TABLE __result1 AS
SELECT 'SELECT' AS `SELECT`, 'FROM' AS `FROM`, 'CONTAINS' AS `CONTAINS`;

CREATE OR REPLACE TABLE __expected1 (
    `SELECT` STRING,
    `FROM` STRING,
    `CONTAINS` STRING,
);
INSERT INTO __expected1 VALUES
  ('SELECT', 'FROM', 'CONTAINS');
