-- CROSS JOIN

CREATE TEMP TABLE t1 (a INT64);
INSERT INTO t1 VALUES (1), (2);

CREATE TEMP TABLE t2 (b INT64);
INSERT INTO t2 VALUES (3), (4);

CREATE OR REPLACE TABLE __result1 AS
SELECT t1.a, t2.b
FROM t1
CROSS JOIN t2;

CREATE OR REPLACE TABLE __expected1 (
    a INT64,
    b INT64,
);
INSERT INTO __expected1 VALUES
  (1, 3),
  (1, 4),
  (2, 3),
  (2, 4);
