-- UNION DISTINCT
CREATE OR REPLACE TABLE __result1 AS
(SELECT 1 AS i UNION DISTINCT SELECT 2)
UNION DISTINCT
SELECT 2;

CREATE OR REPLACE TABLE __expected1 (
    i INT64,
);
INSERT INTO __expected1 VALUES
  (1),
  (2);
