-- Compatibility functions for Trino, needed to run code generated by Joinery.

CREATE FUNCTION memory.joinery_compat.GENERATE_UUID()
RETURNS VARCHAR
NOT DETERMINISTIC
RETURN (
  CAST(UUID() AS VARCHAR)
);

CREATE FUNCTION memory.joinery_compat.SHA256_COMPAT(input VARCHAR)
RETURNS VARBINARY
CALLED ON NULL INPUT
RETURN (
  SHA256(TO_UTF8(input))
);

-- This is how we'd define a version for BINARY values, but doing so causes
-- `SHA256_COMPAT(NULL)` to fail with:
--
-- > Could not choose a best candidate operator. Explicit type casts must be
-- > added.
--
-- `CALLED ON NULL INPUT` doesn't seem to help?
--
-- CREATE FUNCTION memory.joinery_compat.SHA256_COMPAT(input VARBINARY)
-- RETURNS VARBINARY
-- RETURN (
--   SHA256(input)
-- );

CREATE FUNCTION memory.joinery_compat.TO_HEX_COMPAT(input VARBINARY)
RETURNS VARCHAR
RETURNS NULL ON NULL INPUT
RETURN (
  LOWER(TO_HEX(input))
);
